name: Java CI and Automated Extraction
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Run setup script
      run: ./setup.sh

    - name: Run Extraction
      run: |
        cd extractor
        ./gradlew run --args="../.ci-temp/checkstyle" --info

    - name: Check git changes
      run: ./.github/workflows/commands.sh git-diff

    - name: Commit and Push Changes
      if: steps.git-check.outputs.changes > 0 && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Automated extraction update"
        git push origin ${{ github.ref_name }}


    - name: Upload build reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: |
          extractor/build/reports
          extractor/build/test-results